/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52
 * Generated at: 2014-03-20 14:50:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.NewsHome;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"author\" content=\"\">\r\n");
      out.write("\r\n");
      out.write("    <title>International Class of School of Software</title>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap core CSS -->\r\n");
      out.write("    <link href=\"css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("    <!-- Add custom CSS here -->\r\n");
      out.write("    <link href=\"css/stylish-portfolio.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\t\r\n");
      out.write("    <!-- Side Menu -->\r\n");
      out.write("    <a id=\"menu-toggle\" href=\"#\" class=\"btn btn-primary btn-lg toggle\"><i class=\"fa fa-bars\"></i></a>\r\n");
      out.write("    <div id=\"sidebar-wrapper\">\r\n");
      out.write("        <ul class=\"sidebar-nav\">\r\n");
      out.write("            <a id=\"menu-close\" href=\"#\" class=\"btn btn-default btn-lg pull-right toggle\"><i class=\"fa fa-times\"></i></a>\r\n");
      out.write("            <li class=\"sidebar-brand\"><a href=\"http://software.hit.edu.cn\">School of Software</a>\r\n");
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("            <a>Please Log In</a>\r\n");
      out.write("            <div class=\"form-div\">\r\n");
      out.write("              <form class=\"form-signin\" role=\"form\" action=\"/ICOFSOFTWARE/LoginServlet\" method=\"post\">\r\n");
      out.write("                <input type=\"text\" name=\"useremail\" class=\"form-control\" placeholder=\"Email address\" required=\"\" autofocus=\"\">\r\n");
      out.write("                <input type=\"password\" name=\"userpwd\" class=\"form-control\" placeholder=\"Password\" required=\"\">\r\n");
      out.write("                <div class=\"checkbox\">\r\n");
      out.write("                <label>\r\n");
      out.write("                <input type=\"checkbox\" value=\"remember-me\"> Remember me\r\n");
      out.write("                </label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button class=\"btn btn-default btn-sm\" type=\"submit\" name=\"submit\" value=\"login\">Sign In</button>\r\n");
      out.write("                <button class=\"btn btn-default btn-sm\" type=\"submit\">Register</button>\r\n");
      out.write("              </form> \r\n");
      out.write("            </div>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            </li>\r\n");
      out.write("            <li><a href=\"#top\">Home</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li><a href=\"#about\">Introduction</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li><a href=\"#services\">Navigation</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li><a href=\"#portfolio\">Pictures</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li><a href=\"#contact\">Contact</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            \r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /Side Menu -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Full Page Image Header Area -->\r\n");
      out.write("    <div id=\"top\" class=\"header\">\r\n");
      out.write("        <div class=\"vert-text\">\r\n");
      out.write("            <!-- <h1>Start Bootstrap</h1>-->\r\n");
      out.write("            <h1 class=\"white-font\"> Welcome to International Class</h1>\r\n");
      out.write("            <h2 class=\"white-font\">\r\n");
      out.write("                <em>School of Software</em> in HIT<!--\r\n");
      out.write("                <em>You</em> Make Them Better--></h2>\r\n");
      out.write("            <h2 class=\"white-font\"> 哈工大软件学院国际班</h2>\r\n");
      out.write("            <a href=\"#about\" class=\"btn btn-default btn-lg\">Find Out More</a>\r\n");
      out.write("            <a id=\"login-bt\"class=\"btn btn-default btn-lg\">Log in</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /Full Page Image Header Area -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Intro -->\r\n");
      out.write("    <div id=\"about\" class=\"intro\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6 col-md-offset-3 text-center\">\r\n");
      out.write("                    <h2>International Cooperation</h2>\r\n");
      out.write("                    <h2>国际合作简介</h2>\r\n");
      out.write("                    <p class=\"lead\">HIT School of Software and many famous universities of United States, Ireland, Germany, Britain, France, Sweden, Switzerland, Italy, Japan, Korea and other countries, as well as IBM, Microsoft, Intel, HP, AutoDesk and other well-known international IT companies have signed a cooperation agreement, about cooperation and exchange projects.</p>\r\n");
      out.write("                    <p class=\"lead\">哈工大软件学院已先后与美国、爱尔兰、德国、英国、法国、瑞典、瑞士、意大利、日本、韩国等多个国家的著名高校以及IBM、Microsoft、Intel、HP、AutoDesk等国际知名IT公司签订了合作协议，开展合作交流项目。<a target=\"_blank\" href=\"http://software.hit.edu.cn/cooperation/show/39.aspx\">Learn More>> </a></p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /Intro -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Services -->\r\n");
      out.write("    <div id=\"services\" class=\"services\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-4 col-md-offset-4 text-center\">\r\n");
      out.write("                    <h2></h2>\r\n");
      out.write("                    <hr>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-2 col-md-offset-2 text-center\">\r\n");
      out.write("                    <div class=\"service-item\">\r\n");
      out.write("                        <a href=\"http://software.hit.edu.cn\"><i class=\"service-icon fa fa-home\"></i></a>\r\n");
      out.write("                        <h4>News Home</h4>\r\n");
      out.write("                        <p>Do you want to find out more news or information about the International Class of School of Software in HIT? Click Here!</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-2 text-center\">\r\n");
      out.write("                    <div class=\"service-item\">\r\n");
      out.write("                        <i class=\"service-icon fa fa-group\"></i>\r\n");
      out.write("                        <h4>Alumnus Circle</h4>\r\n");
      out.write("                        <p>Need to know what our alumnus are doing now? Need to make some friends from seniors or Juniors? Click Here!</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-2 text-center\">\r\n");
      out.write("                    <div class=\"service-item\">\r\n");
      out.write("                        <i class=\"service-icon fa fa-search\"></i>\r\n");
      out.write("                        <h4>Search</h4>\r\n");
      out.write("                        <p>Search the information you want to know.</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-2 text-center\">\r\n");
      out.write("                    <div class=\"service-item\">\r\n");
      out.write("                        <i class=\"service-icon fa fa-envelope\"></i>\r\n");
      out.write("                        <h4>Email</h4>\r\n");
      out.write("                        <p>Do you want to contact us? You can email us from here!</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /Services -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Callout -->\r\n");
      out.write("    <div class=\"callout\">\r\n");
      out.write("        <div class=\"vert-text\">\r\n");
      out.write("            <h1>What's Next?</h1>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /Callout -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Portfolio -->\r\n");
      out.write("    <div id=\"portfolio\" class=\"portfolio\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-4 col-md-offset-4 text-center\">\r\n");
      out.write("                    <h2>Pictures</h2>\r\n");
      out.write("                    <h3>国际班图片展示</h3>\r\n");
      out.write("                    <hr>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-4 col-md-offset-2 text-center\">\r\n");
      out.write("                    <div class=\"portfolio-item\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img class=\"img-portfolio img-responsive\" src=\"img/SoftwareBuilding.jpeg\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <h4>Building of School</h4>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4 text-center\">\r\n");
      out.write("                    <div class=\"portfolio-item\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img class=\"img-portfolio img-responsive\" src=\"img/MainBuilding2.jpg\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <h4>Building of MainBuilding in HIT</h4>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-4 col-md-offset-2 text-center\">\r\n");
      out.write("                    <div class=\"portfolio-item\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img class=\"img-portfolio img-responsive\" src=\"img/Leader.jpg\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <h4>Professors of School</h4>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-4 text-center\">\r\n");
      out.write("                    <div class=\"portfolio-item\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img class=\"img-portfolio img-responsive\" src=\"img/Leader2.jpg\">\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <h4>Professors of School</h4>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /Portfolio -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Call to Action -->\r\n");
      out.write("        <div class=\"call-to-action\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6 col-md-offset-3 text-center\">\r\n");
      out.write("                    <h3>The map below is the <em>accurate Location</em> of our school and some <em>Contact Information</em>.</h3>\r\n");
      out.write("                    <!--<a href=\"#\" class=\"btn btn-lg btn-default\">Click Me!</a>-->\r\n");
      out.write("                    <a href=\"#top\" class=\"btn btn-lg btn-primary\">Back to Top</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("   \r\n");
      out.write("    <!-- /Call to Action -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Map -->\r\n");
      out.write("    <div id=\"contact\" class=\"map\">\r\n");
      out.write("        <iframe width=\"100%\" height=\"100%\" frameborder=\"0\" scrolling=\"no\" marginheight=\"0\" marginwidth=\"0\" src=\"https://maps.google.com/maps?f=q&amp;source=s_q&amp;hl=en&amp;geocode=&amp;q=Harbin Institute of Technology,+Inc.,+Harbin,+China&amp;aq=0&amp;oq=twitter&amp;sll=126.628932,45.736455&amp;sspn=0.128789,0.264187&amp;ie=UTF8&amp;hq=Harbin Institute of Technology,+Inc.,+Harbin,+China&amp;t=m&amp;z=15&amp;iwloc=A&amp;output=embed\"></iframe>\r\n");
      out.write("        <br />\r\n");
      out.write("        <small>\r\n");
      out.write("            <a href=\"https://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;geocode=&amp;q=Harbin Institute of Technology,+Inc.,+Harbin,+China&amp;aq=0&amp;oq=twitter&amp;sll=126.628932,45.736455&amp;sspn=0.128789,0.264187&amp;ie=UTF8&amp;hq=Harbin Institute of Technology,+Inc.,+Harbin,+China&amp;t=m&amp;z=15&amp;iwloc=A\"></a>\r\n");
      out.write("        </small>\r\n");
      out.write("        </iframe>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- /Map -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-6 col-md-offset-3 text-center\">\r\n");
      out.write("                    <ul class=\"list-inline\">\r\n");
      out.write("                        <li><i class=\"fa fa-facebook fa-3x\"></i>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><i class=\"fa fa-twitter fa-3x\"></i>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><i class=\"fa fa-dribbble fa-3x\"></i>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                    <div class=\"top-scroll\">\r\n");
      out.write("                        <a href=\"#top\"><i class=\"fa fa-circle-arrow-up scroll fa-4x\"></i></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <hr>\r\n");
      out.write("                    <p>Copyright &copy; School of Software, Created by Team J.K. 2014</p>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- /Footer -->\r\n");
      out.write("\r\n");
      out.write("    <!-- JavaScript -->\r\n");
      out.write("    <script src=\"js/jquery-1.10.2.js\"></script>\r\n");
      out.write("    <script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Custom JavaScript for the Side Menu and Smooth Scrolling -->\r\n");
      out.write("    <script>\r\n");
      out.write("    $(\"#menu-close\").click(function(e) {\r\n");
      out.write("        e.preventDefault();\r\n");
      out.write("        $(\"#sidebar-wrapper\").toggleClass(\"active\");\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("    <script>\r\n");
      out.write("    $(\"#menu-toggle\").click(function(e) {\r\n");
      out.write("        e.preventDefault();\r\n");
      out.write("        $(\"#sidebar-wrapper\").toggleClass(\"active\");\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("    <script>\r\n");
      out.write("    $(\"#login-bt\").click(function(e) {\r\n");
      out.write("        e.preventDefault();\r\n");
      out.write("        $(\"#sidebar-wrapper\").toggleClass(\"active\");\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("    <script>\r\n");
      out.write("    $(function() {\r\n");
      out.write("        $('a[href*=#]:not([href=#])').click(function() {\r\n");
      out.write("            if (location.pathname.replace(/^\\//, '') == this.pathname.replace(/^\\//, '') || location.hostname == this.hostname) {\r\n");
      out.write("\r\n");
      out.write("                var target = $(this.hash);\r\n");
      out.write("                target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');\r\n");
      out.write("                if (target.length) {\r\n");
      out.write("                    $('html,body').animate({\r\n");
      out.write("                        scrollTop: target.offset().top\r\n");
      out.write("                    }, 1000);\r\n");
      out.write("                    return false;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
